### ISSUE TITLE
After Installing Error : _reactNative.AsyncStorage.getItem(..).then(..).done is not a function

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [capitalone/react-native-pathjs-charts#173]
hi,

after installing and link this , i got AsyncStorage error,

 _reactNative.AsyncStorage.getItem(..).then(..).done is not a function

React-native version : latest

**Comment by marzolfb** [comment]
This seems to have nothing to do with this library. When you say "latest" for react-native version, what version is that specifically? Are you able to build/run the included example app just fine? If so, do you want to compare how you are setup with your own app and compare it to the example app that works fine?

**Comment by sehranhas** [comment]
I have the same issue. I wasn't able to run the example app either. Is this library compatible with react native v0.49.2?

**Comment by sehranhas** [comment]
@nilaybrahmbhatt found the problem just remove the `.done()` part

**Comment by phillbaker** [comment]
I believe this actually is an issue with `react-native-pathjs-charts`. After requiring/importing an element (e.g. `import { SmoothLine } from 'react-native-pathjs-charts'`), `Promise.prototype.done` becomes `undefined`. Commenting out the import leads to the built-in react-native promise coming back (which does define `done`). 

I think it's related to the babel-polyfill introduced in https://github.com/capitalone/react-native-pathjs-charts/pull/85, [looking at the docs](https://babeljs.io/docs/usage/polyfill/#details) I'm guessing that babel-polyfill overrides the react native global promise object with its own.

This seems related to https://github.com/capitalone/react-native-pathjs-charts/issues/195.

**Comment by phillbaker** [comment]
It looks like [an alternative solution](https://github.com/facebook/react-native/issues/4676#issuecomment-340290485) to #62 might be:

```
// index.android.js
import 'core-js/es6/symbol';
import 'core-js/fn/symbol/iterator';
```

Note that the other issues linked to in that comment have been fixed in https://github.com/facebook/react-native/commit/165b38ab7abdf9d769efddde39da35a03564284b.

**Comment by marzolfb** [comment]
Thank you very much @phillbaker - your feedback/solution was very helpful in addressing this issue. I'll try to get #211 merged in and published to npm in the next 2-3 days.

**Comment by phillbaker** [comment]
Thanks, beat me to a PR :)!

**Comment by marzolfb** [comment]
Closing now that #211 has been merged into master
